<h2>Contact List</h2>
<table >
<thead>
<tr>
<th>First Name</th>
<th>Last Name</th>
<th>Job Title</th>
<th>Email</th>
<th>Phone</th>
<th>Address</th>
<th>City</th>
<th>State</th>
</tr>
</thead>
<?php
foreach ($contacts as $contact) {
	echo "<tr>";
	echo "<td>" . $contact->first_name . "</td>";
	echo "<td>" . $contact->last_name . "</td>";
	echo "<td>" . $contact->job_title . "</td>";
	echo "<td>" . $contact->email . "</td>";
	echo "<td>" . $contact->phone . "</td>";
	echo "<td>" . $contact->address . "</td>";
	echo "<td>" . $contact->city . "</td>";
	echo "<td>" . $contact->state . "</td>";
	echo "</tr>";
}
?>
</table>
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>