<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Pscd\Module'                        => __DIR__ . '/Module.php',
    'Pscd\Controller\ContactController' => __DIR__ . '/src/Pscd/Controller/ContactController.php',
    'PscdTest\Framework\TestCase'        => __DIR__ . '/tests/Pscd/Framework/TestCase.php',
    'PscdTest\SampleTest'                => __DIR__ . '/tests/Pscd/SampleTest.php',
);
